### ISSUE TITLE
XTools edit counter needs a more descriptive label

### ISSUE THREAD

**Issue by JJMC89** [MusikAnimal/MoreMenu#3]
The XTools edit counter needs a more descriptive label. `Analysis` is too vague.

https://github.com/MusikAnimal/MoreMenu/blob/0c0a3078e545c3282fe9b1ccffdfe11a21c14a66/src/MoreMenu.user.js#L119-L121

https://github.com/MusikAnimal/MoreMenu/blob/0c0a3078e545c3282fe9b1ccffdfe11a21c14a66/src/MoreMenu.messages.en.js#L8

**Comment by JJMC89** [comment]
Suggestions:
- Edit counter – XTools
- Analysis – XTools

**Comment by MusikAnimal** [comment]
Good point. There's an existing message for "Analysis – XTools", so I will go with that :) Thanks.
